# Generated by Django 3.0.5 on 2020-04-06 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapresult',
            name='guid',
            field=models.CharField(default=uuid.UUID('86a0ea55-e220-4acb-aa92-d1086d61492f'), max_length=36, primary_key=True, serialize=False, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='mapresult',
            name='job',
            field=models.CharField(max_length=150, verbose_name='Job'),
        ),
    ]
