# Generated by Django 3.0.5 on 2020-04-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0002_auto_20200406_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapresult',
            name='guid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='GUID'),
        ),
    ]
