# Generated by Django 3.0.5 on 2020-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0004_auto_20200408_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renderjob',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
