# Generated by Django 3.0.5 on 2020-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0005_auto_20200408_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderjob',
            name='media_type',
            field=models.CharField(default='image/png', max_length=100, verbose_name='Media type'),
        ),
    ]
