# Generated by Django 3.1.5 on 2021-01-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0006_renderjob_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderjob',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
