# Generated by Django 3.1.5 on 2021-01-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0007_renderjob_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapresult',
            name='file',
            field=models.FileField(null=True, upload_to='maps'),
        ),
    ]
