# Generated by Django 3.1.5 on 2021-01-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0008_auto_20210124_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapresult',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='maps'),
            preserve_default=False,
        ),
    ]
