# Generated by Django 3.1.5 on 2021-02-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0009_auto_20210124_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renderjob',
            name='media_type',
        ),
        migrations.AddField(
            model_name='mapresult',
            name='media_type',
            field=models.CharField(default='image/png', max_length=100, verbose_name='Media type'),
        ),
        migrations.AddField(
            model_name='renderjob',
            name='polygon_count',
            field=models.IntegerField(default=1, verbose_name='Polygon count'),
        ),
    ]
